name: Feature Request
description: Suggest a compatibility, performance, or tooling improvement for SilkMC.
labels: [ "status: needs triage", "type: feature" ]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: true
